#!/usr/bin/env bash

source ../shared/functions.sh

# fire up the docker environment
docker-compose up -d

wait_for_connect

#start connectors
curl -X POST -H "Content-Type: application/json" --data "$(./format_template.py replicator-noschema.json)" http://localhost:8083/connectors
curl -X POST -H "Content-Type: application/json" --data "$(./format_template.py replicator-schema.json)" http://localhost:8083/connectors

