#!/usr/bin/env bash

source ../shared/functions.sh

# fire up the docker environment
docker-compose up -d

wait_for_connect

curl  -X POST -H "Content-Type: application/json" --data @replicator.json http://localhost:8083/connectors

