#!/usr/bin/env bash

# fire up the docker environment

docker-compose up -d

docker-compose logs connect | grep "Kafka Connect started"
while (( $? == 1 ))
do
    sleep 1
    echo "Waiting for connect to be started ..."
    docker-compose logs connect | grep "Kafka Connect started"
done

curl  -X POST -H "Content-Type: application/json" --data @replicator.json http://localhost:8083/connectors

